version: '3.8'

services:
  mongodb:
    container_name: mongo-local 
    image: mongo:latest #use the latest image
    restart: always
    environment: # set require env variables to access mongo
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWD
    ports:
      - '$DB_PORT:$DB_PORT'
  # Mongo Express Service
  mongo-express:
    container_name: mongo-express-local
    image: mongo-express:latest #use the latest image
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWD
      - ME_CONFIG_MONGODB_SERVER=mongo-local
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - '$EXPRESS_PORT:$EXPRESS_PORT'